-- ==========================================
-- HealSmart - Interface Options Config Panel (v0.6.0)
-- ==========================================

local configPanel = CreateFrame("Frame", "HealSmartConfigPanel", UIParent)
configPanel.name = "HealSmart"

-- Fetch the version string dynamic checkpoint directly from the .toc metadata sheet
local addonVersion = C_AddOns and C_AddOns.GetAddOnMetadata and C_AddOns.GetAddOnMetadata("HealSmart", "Version") or "0.6.0"

-- Create Title Layout Text
local creditsText = configPanel:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
creditsText:SetPoint("TOPLEFT", 16, -6)
creditsText:SetText("HealSmart v" .. addonVersion .. " - by mimma @ EU-Pyrewood Village")
creditsText:SetTextColor(0.75, 0.75, 0.75, 1.0) -- Beautiful silver text overlay layout

local title = configPanel:CreateFontString(nil, "OVERLAY", "GameFontNormalLarge")
title:SetPoint("TOPLEFT", creditsText, "BOTTOMLEFT", 0, -14)
title:SetText("HealSmart Configuration")

local subText = configPanel:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
subText:SetPoint("TOPLEFT", title, "BOTTOMLEFT", 0, -8)
subText:SetText("Customize your multi-session layout behaviors and history limits below.")

-- Create the Session Limit Slider Object (Range updated to 5-100)
local slider = CreateFrame("Slider", "HealSmartSessionSlider", configPanel, "OptionsSliderTemplate")
slider:SetPoint("TOPLEFT", subText, "BOTTOMLEFT", 0, -30)
slider:SetMinMaxValues(5, 100) -- NEW: Expanded max limit to 100 sessions
slider:SetValueStep(1)
slider:SetObeyStepOnDrag(true)

-- Attach descriptive labels to the slider frame
local sliderLabel = slider:CreateFontString(nil, "OVERLAY", "GameFontNormalSmall")
sliderLabel:SetPoint("BOTTOMLEFT", slider, "TOPLEFT", 0, 4)
sliderLabel:SetText("Max Saved Sessions:")

local lowText = _G[slider:GetName() .. "Low"]
if lowText then lowText:SetText("5") end

local highText = _G[slider:GetName() .. "High"]
if highText then highText:SetText("100") end -- NEW: Text updated to match the 100 limit checkpoint

local valueText = slider:CreateFontString(nil, "OVERLAY", "GameFontHighlightSmall")
valueText:SetPoint("LEFT", slider, "RIGHT", 10, 0)

-- Function to handle value changes smoothly
slider:SetScript("OnValueChanged", function(self, value)
    local roundedValue = math.floor(value + 0.5)
    valueText:SetText(tostring(roundedValue))
    
    -- Sync the configuration variable inside your global settings database live
    if HealSmartSettings then
        HealSmartSettings.maxSessionsLimit = roundedValue
        -- Update the runtime constant path dynamically
        HEALSMART_MAX_SAVED_SESSIONS = roundedValue
    end
end)

-- Register the completed frame panel into Blizzards Addon Options sub-menu hierarchy
if Settings and Settings.RegisterCanvasLayoutCategory then
    -- Modern Classic Era API integration (Dragonflight engine framework)
    local category = Settings.RegisterCanvasLayoutCategory(configPanel, configPanel.name)
    Settings.RegisterAddOnCategory(category)
    
    -- FIXED: Secure and store the internal numeric Category ID generated by Blizzard
    HealSmart_ConfigCategoryID = category:GetID()
else
    -- Retro legacy engine fallback support paths
    InterfaceOptions_AddCategory(configPanel)
end

-- Hook an onboarding loader listener to populate default slider states upon login loading completions
local configLoader = CreateFrame("Frame")
configLoader:RegisterEvent("ADDON_LOADED")
configLoader:SetScript("OnEvent", function(self, event, addonName)
    if addonName == "HealSmart" then
        if HealSmartSettings then
            if not HealSmartSettings.maxSessionsLimit then
                HealSmartSettings.maxSessionsLimit = 20
            end
            
            slider:SetValue(HealSmartSettings.maxSessionsLimit)
            HEALSMART_MAX_SAVED_SESSIONS = HealSmartSettings.maxSessionsLimit
        end
        self:UnregisterEvent("ADDON_LOADED")
    end
end)

-- end healsmartconfig.lua
